# Project
mod_id=scev
mod_name=Scalar Evolution
mod_version=0.2.0
mod_group_id=lekkit.scev
mod_authors=LekKit (port to 1.21.1)
mod_description=Brings super-scalar RISC-V machines into Minecraft

# Platform
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.209
neo_version_range=[21.1.0,)
loader_version_range=[1,)

# Java
java_version=21

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
