/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
package lekkit.scev.component.describe

import lekkit.scev.component.ComponentRole

/**
 * The result of scanning a component class. This tree is the
 * canonical handoff point between the API surface (annotations + DSL)
 * and the eventual runtime (FUSE / RPC / describe wire format).
 *
 * Nothing here is tied to reflection — once built, a descriptor is
 * pure data and can be serialised, compared, diffed. Tests assert
 * over these structures; the scev runtime (when it lands) consumes
 * them to build the FS tree.
 *
 * "Dead for now" means: we build these, test them, but no runtime
 * walks them yet.
 */

/** Shape of the Lua-side value a property or action arg carries. */
data class ParamSpec(
    /**
     * Canonical Lua-side type name, matching CC's own error messages:
     * `"number"`, `"string"`, `"boolean"`, `"table"`, `"string|bytes"`,
     * `"any"`, or the simpleName of an unknown type.
     */
    val luaType: String,

    /** True when the underlying Java parameter is wrapped in `Optional`. */
    val optional: Boolean = false,

    /**
     * Allowed values when the parameter is an Enum. Lower-cased
     * constant names, matching CC's `LuaValues.checkEnum` convention.
     * Null when the parameter is not an enum.
     */
    val enumValues: List<String>? = null,

    /** Lower bound when the parameter is numeric and bounded. */
    val min: Double? = null,

    /** Upper bound when the parameter is numeric and bounded. */
    val max: Double? = null,
)

/**
 * What shape a method returns. Drives how scev writes the CQE /
 * response on the wire.
 */
enum class ReturnShape {
    /** `void` — no value. */
    NONE,

    /** Primitive or object — single value. */
    ONE,

    /** `Object[]` — arbitrary count, not known statically. */
    MANY,

    /**
     * `MethodResult` / async — pass-through. Could be anything
     * including a yield. The scev dispatcher inspects at runtime.
     */
    DYNAMIC,
}

/**
 * One file under a component's tree that reads (and possibly writes)
 * a single value.
 *
 * Relative [path] is the file's location under the plugin subdir
 * (or the component root when declared top-level). `_label`, `_unit`,
 * `_min`, `_max` sibling files are generated by the runtime from
 * [doc], [unit], [min], [max] when non-null.
 */
data class PropertyDescriptor(
    val path: String,
    /** Type emitted in the `.meta/describe` manifest. */
    val luaType: String,
    val readable: Boolean,
    val writable: Boolean,
    val unit: String? = null,
    val doc: String? = null,
    val min: Double? = null,
    val max: Double? = null,
    /** Allowed enum values, when the underlying type is an Enum. */
    val enumValues: List<String>? = null,
    /** simpleName of the class where the method lives. */
    val declaredBy: String,
)

/**
 * One action file plus its companion result file.
 *
 * Writing to [path] invokes the action with the supplied arguments.
 * The most recent result is available at [resultPath] (default
 * `<path>_result`).
 */
data class ActionDescriptor(
    val path: String,
    val resultPath: String,
    val params: List<ParamSpec>,
    val returnShape: ReturnShape,
    val onTick: Boolean,
    val doc: String? = null,
    val declaredBy: String,
)

/**
 * One event stream. Surfaces as `/dev/scev/<component>.events` (per
 * component) or the aggregate stream on the machine; payloads
 * follow the [paramShape] for structured fields.
 */
data class EventDescriptor(
    val name: String,
    /** Positional shape of the payload tuple, if known. */
    val paramShape: List<ParamSpec> = emptyList(),
    val doc: String? = null,
)

/** One plugin = one subdirectory in the component tree. */
data class PluginDescriptor(
    /** Slug = the subdirectory name. */
    val slug: String,
    /** Capability identifier (or null when plugin has no capability). */
    val capability: String? = null,
    /** simpleName of the plugin's class. */
    val declaredBy: String,
    val properties: List<PropertyDescriptor>,
    val actions: List<ActionDescriptor>,
    val events: List<EventDescriptor> = emptyList(),
    val doc: String? = null,
)

/** Top-level descriptor for a whole component. */
data class ComponentDescriptor(
    /** User-visible name — matches `/sys/scev/by-label/<name>`. */
    val name: String,
    val role: ComponentRole,
    /** Fully-qualified Java class name. */
    val declaringClass: String,
    /** Top-level (non-plugin) properties. */
    val rootProperties: List<PropertyDescriptor>,
    /** Top-level actions. */
    val rootActions: List<ActionDescriptor>,
    /** Top-level events. */
    val rootEvents: List<EventDescriptor> = emptyList(),
    val plugins: List<PluginDescriptor>,
    val doc: String? = null,
) {
    /**
     * Convenience: flatten every property in the descriptor, regardless
     * of whether it's at root or under a plugin. Used by tests and by
     * the eventual runtime's debug-dump paths. Paths are prefixed with
     * the plugin slug when nested.
     */
    fun allProperties(): List<Pair<String, PropertyDescriptor>> {
        val out = ArrayList<Pair<String, PropertyDescriptor>>(
            rootProperties.size + plugins.sumOf { it.properties.size },
        )
        for (p in rootProperties) out.add(p.path to p)
        for (plugin in plugins) {
            for (p in plugin.properties) out.add("${plugin.slug}/${p.path}" to p)
        }
        return out
    }

    /** Like [allProperties] but for actions. */
    fun allActions(): List<Pair<String, ActionDescriptor>> {
        val out = ArrayList<Pair<String, ActionDescriptor>>(
            rootActions.size + plugins.sumOf { it.actions.size },
        )
        for (a in rootActions) out.add(a.path to a)
        for (plugin in plugins) {
            for (a in plugin.actions) out.add("${plugin.slug}/${a.path}" to a)
        }
        return out
    }
}
